server:
  port: 9090
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true

custom:
  jwt:
    secret: 77397A24432646294A404E635266556A586E3272357538782F4125442A472D4B
    expiration: 7200000
    expiration_refresh: 2592000000


aws:
  region: ru-central1
  accessKeyId: ${AWS_KEY_ID}
  secretAccessKey: ${AWS_KEY_SECRET}
  bucket-name: coffee-bucket